README.md
The `docker run` scripts in the `README` point to a `--net=`
configuration parameter whereas the Docker Run documentation
(https://docs.docker.com/engine/reference/run/) calls the
configuration variable `--network`. Update the `README` to
reflect the correct configuration parameter name.
---
I am very new to Docker and this is my first time trying to run a Docker image on a server. When trying to set up Plex Media Server using the **Host Networking** instructions, it did not work. However, once I changed `--net` to `--network`, everything started working as expected. Hence, I'm pretty sure that there is a typo in the `README`. If so, this PR should fix that problem.
=> Fix `docker run --network` parameter

Dockerfile
This package is necessary in order to provide zoneinfo and support
for using the TZ environment variable.
=> Ensures 'tzdata' package is installed.

root/etc/cont-init.d/45-plex-hw-transcode-and-connected-tuner
Discussion came up in #41.  We should check dvb devices for permissions as well.
@Sparticuz, can you check these changes to see if this works for you?  I don't have the hardware to test with.  Likely best tested without the dri devices passed into the container.
=> Also check connected tuners for video group.

README.md
The README instructions for 'ADVERTISE_IP' had an extra word `be` that needed to be removed. This commit removes it.  :)
=> Remove extraneous 'be' in README

.gitignore, Dockerfile, Dockerfile.arm64, root/etc/cont-init.d/50-plex-update, root/installBinary.sh, root/plex-common.sh
(EDIT 1: Making my PR explanations more understandable)
Hi Plex Community,
I have a suggestion for the official Plex Docker Image, which is to make it available for different platforms other than Ubuntu/amd64.
**Modification suggested by my branch:**
- ADD: Add environment variables (ARGs in Dockerfile) to be able to create Docker Images for almost any OS and architecture supported by Plex Media Server by only changing these environment variables ;
- ADD: Add a Dockerfile for ubuntu/arm64 platforms ;
- EDIT: Update S6-Overlay to a more recent version, which now supports new architectures like ARM ;
- EDIT: Update package URLs to the latest Plex Download API
> PLEX_BUILD and PLEX_DISTRO environment variables correspond to the "build" and "distro" variables listed in the API 5 JSON, …
=> Add arm64 support and Update Plex Download URLs to latest API

root/plex-common.sh
Mitigates an ARM installation issue:
```dpkg: error processing archive /tmp/plexmediaserver.deb (--install):
package architecture (arm64) does not match system (armhf)
```
=> Add --force-architecture to dpkg installation command

root/healthcheck.sh
If Plex is running and accepting TCP connections on 32400 but is unable to send a response, curl will wait indefinitley until it does.
Adding `--max-time 60` sets an upper limit for how long curl will wait for a response.  If this is reached, curl will exit with an error status which lines up with the existing use of `--fail` to catch HTTP error responses.
=> Add --max-time 100 to healthcheck

root/etc/cont-init.d/40-plex-first-run
It is possible to end up with a long startup period if symlinks have incorrect ownership as they've never corrected by this script currently so each new docker pull they are found by find and the target ownership is updated (despite being correct) causing a delay in startup
This change assumes that all symlink targets are also within the /config directory tree otherwise the targets could be left unchanged as chown no longer follows the links. Alternatively we could run the command twice once for targets & once for symlinks themselves.
=> Change chown to modify ownership symlinks

README.md, docker-compose-bridge.yml.template
We want docker-compose and documentation aligned with Dockerfile commit https://github.com/plexinc/pms-docker/commit/61178f762e30348de2753cdad40df6e5b3ac6555
=> Remove unused port 3005 from docker-compose template and readme

CODE_OF_CONDUCT.md, charts/plex-media-server/.helmignore, charts/plex-media-server/Chart.yaml, charts/plex-media-server/LICENSE, charts/plex-media-server/README.md, charts/plex-media-server/templates/NOTES.txt, charts/plex-media-server/templates/_helpers.tpl, charts/plex-media-server/templates/configmap-init-script.yaml, charts/plex-media-server/templates/ingress.yaml, charts/plex-media-server/templates/service.yaml, charts/plex-media-server/templates/serviceaccount.yaml, charts/plex-media-server/templates/statefulset.yaml, charts/plex-media-server/values.yaml
closes: https://github.com/plexinc/operations/issues/2886
Adds a new method to deploy a PMS container to a Kubernetes cluster. 
This chart will deploy a `StatefulSet` with a single instance of of PMS.
Data volumes can be mounted by creating `PersistentVolume`s or by using the `rclone` sidecars to be able to easily mount drives from arbitrary locations that may not have Kubernetes drivers.
By default this chart will create a PMS service _internal_ to the cluster that is published on the standard PMS port.
However, this will now allow direct external connections to PMS. 
A builtin ingress controller has been provided that will allow PMS to be accessed over the standard HTTP(s) ports, this will require manually reconfiguring the PMS instance to [advertise using this …
=> feat: add a helm chart to deploy PMS Kubernetes 

.github/CODEOWNERS, .github/workflows/helm.yaml
In #82 a helm chart was added but it is not currently installable directly from helm without being packaged properly. 
This adds a github workflow that will automatically package and publish the chart using github pages. This workflow was modified from the one used by [ingress-nginx](https://github.com/kubernetes/ingress-nginx/blob/main/.github/workflows/helm.yaml)
Steps that are still needed:
=> feat: add a workflow to package and release the helm chart

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/statefulset.yaml
This fixes the problem where the tolerations were at the `.spec.tolerations` level but should have been at `.spec.template.spec.tolerations`
This will be released as a patch version bump of the chart
=> fix: the tolerations block was at the wrong level in the statefulset

.github/linters/ct.yaml, .github/workflows/lint-test.yaml
Add a `ct` job to lint and test charts using helm/chart-testing. By default, any PRs that modify `charts/*` will be linted and the chart installed against a kind cluster to check for correctness.
=> build: add chart-testing workflow

.github/linters/ct.yaml
Helm argument is redundant during lint and fails the checks.
=> build: fix ct lint steps

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/statefulset.yaml, charts/plex-media-server/values.yaml
I have an existing persistent volume and persistent volume claim with my PMS database. I want to use this pvc with the PMS helm chart.
This PR uses a common helm pattern where the user can provide the name of a pre existing volume claim and the chart will configure the PMS container to use that claim instead of creating a volumeClaimTemplate.
=> Helm chart: Add the ability to use a pre existing peristent volume claim

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/statefulset.yaml, charts/plex-media-server/values.yaml
Currently there is no way to annotate the pods in PMS' StatefulSet. This adds a chart value to do precisely that. My use case is that I want to add Plex to my Linkerd service mesh, which can be done through the `linkerd.io/inject` annotation.
=> feat: allow setting pod annotations

charts/plex-media-server/Chart.yaml, charts/plex-media-server/README.md, charts/plex-media-server/templates/statefulset.yaml, charts/plex-media-server/values.yaml
This option might be interesting for those that are running a GPU within their kubernetes cluster and want to be able to specify the runtimeClassName manually.
```
---
apiVersion: v1
kind: Pod
metadata:
name: nbody-gpu-benchmark
namespace: default
spec:
restartPolicy: OnFailure
runtimeClassName: nvidia
containers:
- name: cuda-container
image: nvcr.io/nvidia/k8s/cuda-sample:nbody
args: ["nbody", "-gpu", "-benchmark"]
resources:
limits:
nvidia.com/gpu: 1
env:
- name: NVIDIA_VISIBLE_DEVICES
value: all
- name: NVIDIA_DRIVER_CAPABILITIES
value: all
```
=> Add runtimeClassName

root/installBinary.sh
Fix bug injected into #107 that altered the `PLEX_BUILD` variable causing arm64 docker builds to fail to find arm64 images on the plex download server.
```
$ docker build --platform linux/arm64 --no-cache -t plexinc/pms-docker:latest .
Sending build context to Docker daemon  152.1kB
Step 1/20 : FROM ubuntu:20.04
.
.
.
Step 19/20 : RUN /installBinary.sh
---> Running in 3af3d168a359
Could not get install version
The command '/bin/sh -c /installBinary.sh' returned a non-zero code: 1
```
Here is the original `PLEX_BUILD` which was correct:
https://github.com/plexinc/pms-docker/blob/4d069dc46541f535a6d40fb4e26744fd69060bac/Dockerfile.arm64#L5
```
$ curl -w '%{http_code}' "https://plex.tv/downloads/details/5?build=aarch64&channel=8&distro=debian"
404
```
vs.
```
$ curl -w '%{http_code}' …
```
=> Fix arm64 plex build string

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/service.yaml, charts/plex-media-server/values.yaml
When NodePort is used, plex container is unable to determine the user IP because k8s does NAT.
Because of this, all traffic seems to originate from the cluster itself.
This breaks a bunch of plex functionalities like determining bitrate for transcode and many other that rely on determining if the user is in LAN or WAN.
Setting `externalTrafficPolicy: Local` will allow Plex to determine the actual IP of user because this disables k8s NAT.
But this setting comes with caveats: the pods can only be accessed by the specific Node IP where the pod is running.
Read more here: 
https://kubernetes.io/docs/tasks/access-application-cluster/create-external-load-balancer/#preserving-the-client-source-ip
https://access.redhat.com/solutions/7028639
This is my first time contributing, please let me know …
=> added externalTrafficPolicy to service

charts/plex-media-server/Chart.yaml, charts/plex-media-server/README.md, charts/plex-media-server/templates/service.yaml, charts/plex-media-server/templates/statefulset.yaml, charts/plex-media-server/values.yaml
Please let me know if you would like me to include any default probes.
=> Added liveness and readiness probe to pms container

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/statefulset.yaml
Liveness and readiness probes introduced in #117 are incorrectly nested within the `resources` template. Adding resource limits to the pms chart results in the following error:
```
Error: template: plex-media-server/templates/statefulset.yaml:123:28: executing "plex-media-server/templates/statefulset.yaml" at <.Values.pms.livenessProbe>: nil pointer evaluating interface {}.pms
```
This change fixes that issue.
=> Fix incorrect nesting of liveness and readiness probes

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/ingress.yaml, charts/plex-media-server/values.yaml
By default, the `Ingress` object uses a SSL secret called:
```yaml
{{ include "pms-chart.fullname" . }}-ingress-lets-encrypt
```
Which cannot be customized, as it uses the helm chart name and a suffix `-ingress-lets-encrypt` 🥲
This PR adds an optional variable to the Helm Chart called `ingress.certificateSecret`, to specify that SSL secret name.
By default, this variable has a blank `""` value. If we render the Chart using this default value, the result will be exactly the same as the current value:
```yaml
default (printf "%s-ingress-lets-encrypt" (include "pms-chart.fullname" .))
```
Which is equivalent to:
```yaml
{{ include "pms-chart.fullname" . }}-ingress-lets-encrypt
```
On the other hand, if we specify a string value different from `""`:
```yaml
ingress:
enabled: true …
```
=> Add ingress secret name variable in helm chart

charts/plex-media-server/templates/statefulset.yaml, charts/plex-media-server/values.yaml
The current chart asserts that only a single init container is needed for rclone. This can be adapted for most purposes so long as the specified image contains an entrypoint at /init/init.sh and is meant to be run as an initContainer and not a sidecar container (https://kubernetes.io/docs/concepts/workloads/pods/init-containers/#api-for-sidecar-containers).
There are useful tools that operate on plex's metadata files, bundles, or database that would be best run as sidecar containers (see above), which are functionally init containers with restart policies.
This pull request adds support for additional init containers through an "extraInitContainers" argument that is semantically identical to the existing extraContainers argument.
=> Add support for extra init containers and sidecar containers

charts/plex-media-server/values.yaml
Since a helm chart is made for a specific version of the app, we should specify the image with that version instead of using latest
=> feat: use fixed tag instead of latest in helm chart

.github/linters/ct.yaml, charts/plex-media-server/values.yaml
Update rclone container image version from 1.62 to 1.69 and alpine init container from 3.18 to 3 which is using the latest minor version of alpine. 
Alternatively we can use 3.21 but I would appreciate if you add dependabot or renovate.
=> Update alpine and rclone image tags

charts/plex-media-server/templates/service.yaml
Added the loadBalancerIP key so people using metalLB can set the service ip address that way
=> feat: add service.loadBalancerIP

charts/plex-media-server/Chart.yaml, charts/plex-media-server/README.md, charts/plex-media-server/templates/service.yaml, charts/plex-media-server/templates/statefulset.yaml, charts/plex-media-server/values.yaml
Consolidating some suggestions from pending PRs.
Closes 
- add `spec.template.spec.dnsConfig` to the main STS (#138)
- update values file for `service.loadBalancerIP` (#137)
- bump pms to `1.41.6.9685-d301f511a` (#130)
- update service.ports indent to match the rest of the manifests
- update README
Bumps chart to v0.10
=> feat: add dnsConfig to StatefulSet 

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/ingress.yaml, charts/plex-media-server/values.yaml
This is a breaking change to the configuration, but it allows for a more flexible TLS configuration.
The current configuration doesn't allow you to configure TLS and also leave the secretName option un-configured which allows you to use the ingress' default TLS certificate.
=> Add more flexible TLS configuration

charts/plex-media-server/Chart.yaml, charts/plex-media-server/templates/ingress.yaml
With the v1 change of the helm chart, the indenting of the tls block shifted right by 2 spaces, effectively removing the tls config altogether. This fixes that by shifting the tls block to the left again by 2 spaces.
=> Fixing indenting of tls config in ingress template

.github/workflows/test-lint.yaml, charts/plex-media-server/Chart.yaml, charts/plex-media-server/README.md, charts/plex-media-server/ci/ci-values.yaml, charts/plex-media-server/templates/statefulset.yaml
Run a static analysis for correctness using [kubeconform]
Use correct indentation for `shareProcessNamespace` stanza on StatefulSet.
Update Chart's README.
Rename `.github/workflows/lint-test.yaml` -> `.github/workflows/test-lint.yaml`
[kubeconform]: https://github.com/yannh/kubeconform
=> build: lint rendered chart using kubeconform

Dockerfile
A default `ubuntu` user was added on ubuntu images 22.10 and up. This breaks permissions on some existing installations due to the default `plex` user now having a different UID (1001).
This removes the default `ubuntu` user and restores the previous UID for the `plex` user.
Regression introduced in #148 
References:
- https://bugs.launchpad.net/cloud-images/+bug/2005129
- https://forums.plex.tv/t/plex-docker-image-should-not-change-permissions-on-mounted-volumes-if-pid-and-gid-is-defined/928780
- https://forums.plex.tv/t/custom-domain-ssl-does-not-work-after-update-to-server-version-1-42-1-10060-4e8b05daf/928405
=> fix(docker): remove default ubuntu user
